server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: for-pets

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

management:
  endpoints:
    web:
      exposure:
        include: health, info