server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: for-pets

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    open-in-view: false

  notifications:
    # broker: direct         # v0
    broker: redis-stream   # v1 전환 시
    # broker: kafka          # v2 전환 시

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  data:
    redis:
      timeout: 2000ms # redis 장애시 빠른 실패처리
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2
          max-wait: 1000ms

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus

  metrics:
    distribution:
      percentiles:
        coupon.issue.duration: 0.95, 0.99
      percentiles-histogram:
        coupon.issue.duration: true

portone:
  store-id: ${PORTONE_STORE_ID:}
  api-secret: ${PORTONE_API_SECRET:}

forpets:
  ai:
    rag:
      collection-name: forpets_reviews
      vector-size: 768
      search-limit: 5
      score-threshold: 0.7
    qdrant:
      base-url: ${QDRANT_BASE_URL:http://localhost:6333}
    gemini:
      embedding-model: text-embedding-004
